//
// Created by 30367 on 2025/11/1.
//

#ifndef INITIALGL_PREDEFINITIONS_H
#define INITIALGL_PREDEFINITIONS_H

#define DEFAULT_TEXTURE_WRAP_S GL_REPEAT
#define DEFAULT_TEXTURE_WRAP_T GL_REPEAT
#define DEFAULT_TEXTURE_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
#define DEFAULT_TEXTURE_MAG_FILTER GL_LINEAR

#define TEXTURE_DIFFUSE_INDEX GL_TEXTURE0
#define TEXTURE_SPECULAR_INDEX GL_TEXTURE1

#define G_BUFFER_POSITION_INDEX GL_TEXTURE0
#define G_BUFFER_NORMAL_INDEX GL_TEXTURE1
#define G_BUFFER_ALBEDO_INDEX GL_TEXTURE2

#endif //INITIALGL_PREDEFINITIONS_H